Repository nstankov-bg/docs.plutus-community.com, pull requests merged in 2021-04, with the labels that each got.

#12 Fixed contributor Github account name
  docs/setup/Ubuntu.md
Labels: Needs Review

#13 Doing Summary Edits
  README.md
  SUMMARY.md
  docs/setup/CabalBuild.md
Labels: Needs Review

#14 Quick'n Dirty Docker
  SUMMARY.md
  book/README.md
  book/SUMMARY.md
  book/docs/intro/Introduction.MD
  book/docs/setup/CabalBuild.md
  book/docs/setup/DockerCompose.md
  book/docs/setup/MacOS.md
  book/docs/setup/Ubuntu.md
  book/docs/setup/Vagrant.md
  book/docs/setup/WindowsWSL.md
  docker/Dockerfile
  docker/docker-compose.yml
  docker/docker-entrypoint.sh
Labels: Needs Review

#15 Docs for setting up haskell-language-server & your favorite editor
  docs/editors/emacs.md
  docs/editors/prerequisites.md
  docs/editors/sublime_text.md
  docs/editors/vscode.md
Labels: documentation

#18 fixing-file-structure-editors
  book/SUMMARY.md
  book/docs/setup/editors/emacs.md
  book/docs/setup/editors/prerequisites.md
  book/docs/setup/editors/sublime_text.md
  book/docs/setup/editors/vscode.md
Labels: Needs Review

#10 Create Lecture1.md
  docs/lectures/Lecture1.md
Labels: documentation

#17 Create Week02-Lecture-Notes.md
  Week02-Lecture-Notes.md
Labels: Needs Review

#19 reorganize-lectures
  book/SUMMARY.md
  book/docs/lectures/Lecture1.md
  book/docs/lectures/Lecture2.md
Labels: Reviewed -- Needs Changes.

#20 Update Lecture2.md
  book/docs/lectures/Lecture2.md
Labels: Needs Review

#21 Added detail to the plutus-pioneer-program workflow
  book/docs/setup/CabalBuild.md
Labels: Needs Review

#16 instructions for how to build local documentation
  book/SUMMARY.md
  book/docs/setup/Ubuntu.md
  book/docs/setup/buildDocumentation.md
Labels: Needs Review

#23 Added instructions for the plutus commit tag
  book/docs/setup/CabalBuild.md
Labels: Needs Review

#25 Some Ubuntu changes
  book/docs/setup/CabalBuild.md
  book/docs/setup/Ubuntu.md
Labels: Needs Review

#27 added instructions to use pre-built docker image compose files
  book/docs/setup/DockerCompose.md
Labels: Needs Review

#26 Create Lecture2Detailed.md
  book/SUMMARY.md
  book/docs/lectures/Lecture2Detailed.md
Labels: Needs Review

#24 Update Lecture2.md
  book/docs/lectures/Lecture2.md
Labels: Needs Review

#29 Update: Lecture1.md add nix-shell reminder to run cabal build
  book/docs/lectures/Lecture1.md
Labels: Approved

#30 Minor adjustment to Nix instructions
  book/docs/setup/Ubuntu.md
Labels: Needs Review

#31 Added info and link to plutus-playground-systemd
  book/docs/setup/Ubuntu.md
Labels: Needs Review

#32 Updated Vim document
  book/SUMMARY.md
  book/docs/setup/editors/vim.md
Labels: Needs Review

#33 Added some trouble shooting points for macOS (Big Sur) setup
  book/docs/setup/MacOS.md
Labels: Approved
