Repository nstankov-bg/docs.plutus-community.com, pull requests merged in 2021-05, with the labels that each got.

#35 Haddock web
  book/SUMMARY.md
  book/docs/setup/buildDocumentation.md
Labels: Needs Review

#36 Added Lecture 3 Docs
  book/SUMMARY.md
  book/docs/lectures/Lecture3.md
Labels: Needs Review

#44 Update Vagrant.md
  book/docs/setup/Vagrant.md
Labels: Approved

#43 Intellij windows
  book/SUMMARY.md
  book/docs/setup/editors/intelliJ-Windows.md
Labels: Approved

#42 Update SUMMARY.md
  book/SUMMARY.md
Labels: Approved

#41 Markdown for IntelliJ IDEA setup on Windows for Plutus
  book/SUMMARY.md
  book/docs/setup/editors/intelliJ-Windows.md
Labels: Reviewed -- Needs Changes.

#46 Added: Lecture5.md
  book/SUMMARY.md
  book/docs/lectures/Lecture5.md
Labels: Needs Review
